### ISSUE TITLE
in android device not working

### ISSUE THREAD

**Issue by smilydronavalli** [punarinta/react-native-sound-level#12]
I got the following error in android device

java.lang.IllegalStateException
        at android.media.MediaRecorder.start(Native Method)
        at com.punarinta.RNSoundLevel.RNSoundLevelModule.start(RNSoundLevelModule.java:63)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:226)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)

kindly help me

**Comment by darknessproduction** [comment]
Same. I think this library not supported anymore

**Comment by punarinta** [comment]
Fixed in 1.4.0: start() now rejects with a descriptive error code (usually a missing RECORD_AUDIO runtime permission) instead of crashing with IllegalStateException. Make sure to request the microphone permission before calling start().
